### ISSUE TITLE
Video not loading from a player on Firefox

### ISSUE THREAD

**Issue by Fejrix** [vaishakhsnair/nyon-stream-web#1]
I have encountered some problems when I tried running this app. The search function works well, but I am not able to play any video. It just hangs at this screen, any possible solutions?

[https://i.imgur.com/VtOb3CA.png](url)

Using:
Windows
Firefox Nightly
localy installed NodeJS, Python

**Comment by vaishakhsnair** [comment]
firefox does not support mkv contianers so it needs to be transcoded on the client or server side which is work in progress.
So the only fix for now is to use a chromium based browser
